"""
LangGraph agent state definition.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Annotated, Any

from langchain_core.messages import BaseMessage
from langchain_core.tools import BaseTool
from langgraph.graph.message import add_messages


@dataclass
class AgentState:
    """State for the LangGraph agent."""

    # Conversation messages (LangGraph manages append-only via add_messages)
    messages: Annotated[list[BaseMessage], add_messages] = field(default_factory=list)

    # Context from the current tab
    focused_tab: str = "slack"
    scope: str = "workspace"  # "tab" | "workspace"

    # Session info
    session_id: str = ""
    branch_id: int = 1

    # Explicit @-mentioned sources from the user message (e.g. ["slack", "meetings"])
    context_mentions: list[str] = field(default_factory=list)

    # Current view context — what the user is looking at right now
    selected_repo: str = ""
    selected_channel: str = ""
    selected_channel_name: str = ""

    # Scope-filtered tools for this invocation (set before graph.astream)
    active_tools: list = field(default_factory=list)

    # OAuth-connected providers (set before graph.astream)
    connected_providers: set = field(default_factory=set)

    # File IDs uploaded via AI panel for this turn (document IDs from /api/ai/upload)
    uploaded_file_ids: list[str] = field(default_factory=list)

    # RAG context retrieved for this turn
    rag_context: list[dict] = field(default_factory=list)

    # Plan steps emitted during this turn
    plan_steps: list[dict] = field(default_factory=list)

    # Thought/reasoning events generated by nodes
    thoughts: list[str] = field(default_factory=list)

    # Pending approval (if any)
    pending_approval: dict | None = None

    # Receipts from tool executions
    receipts: list[dict] = field(default_factory=list)

    # Action cards from write operations
    action_cards: list[dict] = field(default_factory=list)

    # Tool loop counter (incremented each time tools execute)
    tool_loop_count: int = 0

    # Whether we should stop
    should_stop: bool = False
